name: soundconnectmobile
description: BASoundConnect
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  go_router: ^16.1.0
  flutter_riverpod: ^2.6.1
  dio: ^5.9.0
  http: ^1.2.2
  json_annotation: ^4.9.0
  talker_flutter: ^4.9.3
  flutter_secure_storage: ^9.2.4
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  app_links: ^3.5.0

  # 👇 eklendi: talker_flutter ile uyumlu sürümler
  share_plus: ^11.1.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.7.0
  json_serializable: ^6.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/sadece_amblem.png
    - assets/icons/google.png
    - assets/icons/fish.png
